"""V8 P0-d — presentation completeness and Level-2 certification (Detail §4.2).

Compares congruences on the canonical term domain T_t (never raw relation
lists): K_t^eval groups terms by semantic mask; K_t^cert is the congruence
generated by the actor's declared relations/covers, closed under meet/join
congruence propagation.

Term algebra on antichain-DNF representatives:
- meet of terms  (∨A)∧(∨B) = ∨_{a∈A,b∈B} (∧_{i∈a∪b} x_i)  → index-set UNION;
- join of terms  (∨A)∨(∨B) = antichain of the family union A ∪ B.

Level-2 requires ALL six conditions (Detail §4.2); failure downgrades to the
achieved Level 0/1 and the run remains operationally scoreable.
"""

from __future__ import annotations

import time
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

from .masking import (
    CERTIFICATION_INCOMPLETE,
    CertificationIncomplete,
    EvaluatorUniverse,
    ImageFrame,
    TermAntichain,
    build_image_frame,
    enumerate_terms,
    term_mask,
)

LEVEL_0 = 0
LEVEL_1 = 1
LEVEL_2 = 2

NONTRIVIAL_MIN_NONCONSTANT_MASKS = 2
NONTRIVIAL_MIN_QUOTIENT_ELEMENTS = 4


@dataclass(frozen=True)
class DeclaredRelations:
    """Actor-declared relations/covers (Detail §4.2: on canonical term IDs).

    ``equalities``/``refinements``: generator-index pairs (sugar for singleton
    terms).  ``term_equalities``: full term-level identifications (TermAntichain
    pairs) — required when the true structure identifies compound terms (e.g.
    x0∧x2 ≡ ⊥ under a disjoint cover).  ``covers``: (parent index set, member
    index sets) — seeds join(parent) ≡ ∨members.
    """

    equalities: tuple[tuple[int, int], ...] = ()
    refinements: tuple[tuple[int, int], ...] = ()
    covers: tuple[tuple[TermAntichain, tuple[TermAntichain, ...]], ...] = ()  # (parent term, member terms)
    term_equalities: tuple[tuple[TermAntichain, TermAntichain], ...] = ()

    @property
    def declared_count(self) -> int:
        return len(self.equalities) + len(self.refinements) + len(self.covers) + len(self.term_equalities)


def _key(term: TermAntichain) -> tuple:
    """Total order on terms: deterministic canonical sort key."""
    return tuple(sorted(tuple(sorted(member)) for member in term))


_TOP: TermAntichain = frozenset({frozenset()})
_BOTTOM: TermAntichain = frozenset()


def _syntactic_meet(a: TermAntichain, b: TermAntichain) -> TermAntichain:
    """(∨A)∧(∨B) = ∨_{a∈A,b∈B} ∧_{i∈a∪b} — index-set union with absorption.

    top(∅-antichain) is an identity for meet; bottom annihilates.
    """
    from .masking import antichain

    if not a or not b:
        return _BOTTOM
    if a == _TOP:
        return b
    if b == _TOP:
        return a
    return antichain({x | y for x in a for y in b})


def _syntactic_join(a: TermAntichain, b: TermAntichain) -> TermAntichain:
    """(∨A)∨(∨B) = antichain of the family union.

    top absorbs: joining anything with the ∅-antichain yields top.
    """
    from .masking import antichain

    if a == _TOP or b == _TOP:
        return _TOP
    if not a:
        return b
    if not b:
        return a
    return antichain(set(a) | set(b))


def _congruence_closure(
    term_list: Sequence[TermAntichain],
    seeds: Sequence[tuple[int, int]],
    *,
    deadline: float | None = None,
) -> dict[int, int]:
    """Smallest meet/join-congruence on T_t containing the seed identifications.

    Worklist propagation with a hard deadline: exceeding it raises
    CertificationIncomplete (Detail §4.1 — never an approximate result).  The
    k=4 worst case is ~50s uncached; k=5 would be days without the deadline.
    """
    import time as _time

    index = {t: i for i, t in enumerate(term_list)}
    parent = list(range(len(term_list)))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(x: int, y: int) -> bool:
        rx, ry = find(x), find(y)
        if rx != ry:
            parent[max(rx, ry)] = min(rx, ry)
            return True
        return False

    worklist: list[tuple[int, int]] = []
    for x, y in seeds:
        if union(x, y):
            worklist.append((x, y))

    while worklist:
        if deadline is not None and _time.monotonic() > deadline:
            raise CertificationIncomplete("congruence closure exceeded deadline")
        a, b = worklist.pop()
        ta, tb = term_list[a], term_list[b]
        for c in term_list:
            ma, mb = _syntactic_meet(ta, c), _syntactic_meet(tb, c)
            if ma in index and mb in index:
                ia, ib = index[ma], index[mb]
                if union(ia, ib):
                    worklist.append((ia, ib))
            ja, jb = _syntactic_join(ta, c), _syntactic_join(tb, c)
            if ja in index and jb in index:
                ja_i, jb_i = index[ja], index[jb]
                if union(ja_i, jb_i):
                    worklist.append((ja_i, jb_i))
    return {i: find(i) for i in range(len(term_list))}


def _partitions_equal(cert: Mapping[int, int], ev: Mapping[int, int]) -> bool:
    cert_groups: dict[int, set[int]] = {}
    for i, c in cert.items():
        cert_groups.setdefault(c, set()).add(i)
    eval_groups: dict[int, set[int]] = {}
    for i, c in ev.items():
        eval_groups.setdefault(c, set()).add(i)
    return sorted(frozenset(g) for g in cert_groups.values()) == sorted(frozenset(g) for g in eval_groups.values())


@dataclass(frozen=True)
class Level2Report:
    achieved_level: int
    narrow: bool
    conditions: Mapping[str, bool]
    problems: tuple[str, ...] = ()
    stats: Mapping[str, Any] = field(default_factory=dict)


def certify_level2(
    universe: EvaluatorUniverse,
    generator_predicates: Mapping[str, Callable[[str], bool]],
    declared: DeclaredRelations,
    computational_subframe: Any,
    grounding_pairs: Sequence[tuple[str, int, bool]],
    homomorphism_checker: Callable[[ImageFrame], bool] | None = None,
    official_families: Sequence[Callable[[str], bool]] = (),
    *,
    max_terms: int = 20_000,
    max_seconds: float = 30.0,
) -> Level2Report:
    """Run the six Level-2 conditions (Detail §4.2).

    ``grounding_pairs``: (h_id, generator_index, z_in_certified_region).
    ``computational_subframe``: object with executable meet/join over image
    masks (condition 2) and a ``map_term_mask``: int -> int for c_t (condition 3).
    """
    problems: list[str] = []
    names = sorted(generator_predicates)
    k = len(names)
    gen_masks = {i: universe.sigma(generator_predicates[n]) for i, n in enumerate(names)}

    try:
        deadline = time.monotonic() + max_seconds
        terms, _ = enumerate_terms(k, max_terms=max_terms, max_seconds=max_seconds)
        term_list = sorted(terms, key=_key)
        if time.monotonic() > deadline:
            raise CertificationIncomplete("processing exceeded max_seconds")
    except CertificationIncomplete as exc:
        return Level2Report(
            LEVEL_1,
            False,
            {},
            (f"{CERTIFICATION_INCOMPLETE}: {exc}",),
            {"generator_count": k},
        )

    index = {t: i for i, t in enumerate(term_list)}
    gen_term = {i: index[frozenset({frozenset({i})})] for i in range(k)}
    bottom_term = index[frozenset()]
    masks = [term_mask(t, gen_masks, universe.size) for t in term_list]

    # ---- condition 1: K_cert = K_eval on T_t
    seeds: list[tuple[int, int]] = []
    for a, b in declared.equalities:
        seeds.append((gen_term[a], gen_term[b]))
    for a, b in declared.refinements:
        meet_term = _syntactic_meet(frozenset({frozenset({a})}), frozenset({frozenset({b})}))
        seeds.append((gen_term[a], index[meet_term]))
    for parent_term, member_terms in declared.covers:
        join_term: TermAntichain = frozenset()  # bottom as join identity
        for m in member_terms:
            join_term = _syntactic_join(join_term, m)
        seeds.append((index[parent_term], index[join_term]))
    for ta, tb in declared.term_equalities:
        seeds.append((index[ta], index[tb]))
    cert_classes = _congruence_closure(term_list, seeds, deadline=deadline)
    eval_classes = {i: m for i, m in enumerate(masks)}
    same_partition = _partitions_equal(cert_classes, eval_classes)
    conditions: dict[str, bool] = {"congruence_equality": same_partition}
    if not same_partition:
        problems.append("K_cert != K_eval on T_t (condition 1)")

    # ---- quotient image frame
    frame = build_image_frame(universe, gen_masks, max_seconds=max_seconds)

    # ---- condition 2: computational subframe decidable + executable meet/join
    sub_ok = _check_subframe(frame, computational_subframe, problems)

    # ---- condition 3: c_t preserves equal-mask pairs and the lattice ops
    map_fn = getattr(computational_subframe, "map_term_mask", None) if computational_subframe is not None else None
    c_ok = _check_ct(map_fn, masks, frame, problems)

    # ---- condition 4: generator-compatible homomorphism (injected checker)
    homo_ok = True if homomorphism_checker is None else bool(homomorphism_checker(frame))
    conditions["homomorphism"] = homo_ok
    if not homo_ok:
        problems.append("generator-compatible homomorphism failed (condition 4)")

    # ---- condition 5: grounding coverage for every checked (h, z)
    uncovered = [h for h, _, z_ok in grounding_pairs if not z_ok]
    conditions["grounding_coverage"] = not uncovered
    if uncovered:
        problems.append(f"uncovered (h,z) pairs: {uncovered} (condition 5)")

    # ---- condition 6: nontriviality floor
    nonconstant = set(gen_masks.values()) - {0, universe.full_mask()}
    floor_ok = len(nonconstant) >= NONTRIVIAL_MIN_NONCONSTANT_MASKS and frame.size >= NONTRIVIAL_MIN_QUOTIENT_ELEMENTS
    conditions["nontriviality_floor"] = floor_ok
    if not floor_ok:
        problems.append(
            f"nontriviality floor failed: {len(nonconstant)} nonconstant masks "
            f"(<{NONTRIVIAL_MIN_NONCONSTANT_MASKS}) or frame size {frame.size} "
            f"(<{NONTRIVIAL_MIN_QUOTIENT_ELEMENTS}) (condition 6)"
        )

    all_pass = all(conditions.values()) and sub_ok and c_ok
    achieved = LEVEL_2 if all_pass else (LEVEL_1 if sub_ok and c_ok else LEVEL_0)

    # headline gate (Detail §4.2): FamilySep >= 0.5 for instances with official
    # families (the letter sets the gate at >=2 families; we apply it
    # conservatively for ANY nonempty family set — underclaiming is safe).
    # Without family labels the nontriviality floor's 4-element requirement
    # stands.  A Level-2 fragment below the headline gate is validly certified
    # but labeled narrow — it cannot establish C2/C3.
    family_sep = None
    if official_families:
        from .masking import family_separation

        family_sep, _, _ = family_separation(universe, generator_predicates, official_families)
    narrow = achieved == LEVEL_2 and bool(official_families) and (family_sep is None or family_sep < 0.5)
    if narrow:
        problems.append(f"FamilySep={family_sep} < 0.5 at headline gate — certified fragment is narrow (cannot establish C2/C3)")
    return Level2Report(
        achieved_level=achieved,
        narrow=narrow,
        conditions=conditions,
        problems=tuple(problems),
        stats={
            "generator_count": k,
            "term_count": len(term_list),
            "frame_size": frame.size,
            "declared_count": declared.declared_count,
            "family_sep": family_sep,
        },
    )


def _check_subframe(frame: ImageFrame, subframe: Any, problems: list[str]) -> bool:
    if subframe is None:
        problems.append("no computational subframe supplied (condition 2)")
        return False
    for name in ("meet", "join"):
        if not callable(getattr(subframe, name, None)):
            problems.append(f"computational subframe lacks executable {name} (condition 2)")
            return False
    for a in frame.masks:
        for b in frame.masks:
            if subframe.meet(a, b) != frame.meet(a, b) or subframe.join(a, b) != frame.join(a, b):
                problems.append(f"subframe meet/join disagree with masks at ({a:#b},{b:#b}) (condition 2)")
                return False
    return True


def _check_ct(
    map_fn: Callable[[int], int] | None,
    term_masks: Sequence[int],
    frame: ImageFrame,
    problems: list[str],
) -> bool:
    if map_fn is None:
        problems.append("no c_t term-mask mapping supplied (condition 3)")
        return False
    image_of: dict[int, int] = {}
    for m in set(term_masks):
        value = map_fn(m)
        if not isinstance(value, int) or isinstance(value, bool):
            problems.append(f"c_t must map masks to int image ids (got {value!r}) (condition 3)")
            return False
        image_of[m] = value
    # equal-mask terms share one image: map is defined on masks, so constant by
    # construction — the real check is well-definedness on the image frame
    for m, image in image_of.items():
        if m in frame.masks and image not in frame.masks:
            problems.append(f"c_t image {image} outside certified subframe for mask {m:#b} (condition 3)")
            return False
    for a in image_of:
        for b in image_of:
            if image_of[frame.meet(a, b)] != frame.meet(image_of[a], image_of[b]):
                problems.append(f"c_t does not preserve meet at ({a:#b},{b:#b}) (condition 3)")
                return False
            if image_of[frame.join(a, b)] != frame.join(image_of[a], image_of[b]):
                problems.append(f"c_t does not preserve join at ({a:#b},{b:#b}) (condition 3)")
                return False
    if image_of[frame.bottom] != frame.bottom or image_of[frame.top] != frame.top:
        problems.append("c_t does not preserve bottom/top (condition 3)")
        return False
    return True


def relation_precision_recall(
    universe: EvaluatorUniverse,
    generator_predicates: Mapping[str, Callable[[str], bool]],
    declared: DeclaredRelations,
) -> tuple[float, float, int, int]:
    """P_rel / R_rel over generator-pair relations (Detail §4.2).

    P_rel = true declared / declared (eq+ref); R_rel = captured exact relations
    (declared AND true) / relevant exact relations among unordered pairs.
    """
    names = sorted(generator_predicates)
    k = len(names)
    masks = [universe.sigma(generator_predicates[n]) for n in names]

    def holds_eq(a: int, b: int) -> bool:
        return masks[a] == masks[b]

    def holds_ref(a: int, b: int) -> bool:
        return masks[a] & masks[b] == masks[a]

    declared_count = len(declared.equalities) + len(declared.refinements)
    declared_true = 0
    for a, b in declared.equalities:
        declared_true += holds_eq(a, b)
    for a, b in declared.refinements:
        declared_true += holds_ref(a, b)

    relevant = 0
    for a in range(k):
        for b in range(a + 1, k):
            if holds_eq(a, b) or holds_ref(a, b) or holds_ref(b, a):
                relevant += 1

    p_rel = declared_true / declared_count if declared_count else 1.0
    r_rel = declared_true / relevant if relevant else 1.0
    return p_rel, r_rel, declared_true, relevant
